apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  minReadySeconds: 2
  replicas: 3
  selector:
    matchLabels:
      name: nginx
      purpose: release
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - name: nginxc
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP        