apiVersion: v1 
kind: Service
metadata:
  name: srv-demo
  labels:
    app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - ports: 80
      protocol: TCP
      targetPort: 80      