apiVersion: v1 
kind: Service
metadata:
  name: srv-demo
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - nodePort: 80
      ports: 3200
      protocol: TCP
      targetPort: 80      